receivers:
  otlp:
    protocols:
      grpc:
        tls:
          ca_file: /etc/certs/ca.crt
          cert_file: /etc/certs/server.crt
          key_file: /etc/certs/server.key
      http:
        tls:
          ca_file: /etc/certs/ca.crt
          cert_file: /etc/certs/server.crt
          key_file: /etc/certs/server.key

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: jaeger.emqx.net:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
  file:
    path: /etc/otel-collector-tls.json


processors:
  batch:
    # send data immediately
    timeout: 0

extensions:
  health_check:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file]
